# Generated by Django 4.0.5 on 2022-06-28 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=20)),
                ('dummies', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['company'],
            },
        ),
    ]
