# Generated by Django 4.0.5 on 2022-06-28 06:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='death_line',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='project',
            name='progress',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='url_drive',
            field=models.URLField(null=True),
        ),
    ]
